stages:
  data_injestion:
    cmd: python3 src/data_injestion.py
    deps:
    - src/data_injestion.py
    params:
    - data_injestion.test_size
    outs:
    - data/raw

  preprocessing:
    cmd: python3 src/preprocessing.py
    deps:
    - src/preprocessing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_training:
    cmd: python3 src/model_training.py
    deps:
    - src/model_training.py
    - data/processed
    params:
    - model_training.random_state
    - model_training.n_estimators
    outs:
    - model

  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - model
    outs:
    - report

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
params:
- dvclive/params.yaml
