stages:
  data_injestion:
    cmd: python3 src/data_injestion.py
    deps:
    - src/data_injestion.py
    outs:
    - data/raw

  preprocessing:
    cmd: python3 src/preprocessing.py
    deps:
    - src/preprocessing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim
    outs:
    - data/processed

  model_training:
    cmd: python3 src/model_training.py
    deps:
    - src/model_training.py
    - data/processed
    outs:
    - model
  
  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - model
    outs:
    - report

